name: github_activity_feed
description: A Flutter application for viewing GitHub user activity feeds.
publish_to: 'none'

version: 0.0.26

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  google_fonts: ^1.1.0
  url_launcher: ^5.4.7
  github:
    path: ../github.dart
  provider: ^4.1.2
  uuid: ^2.0.4
  path_provider: ^1.6.8
  crypto: any
  cloud_firestore: ^0.13.5
  material_design_icons_flutter: ^4.0.5245
  rxdart: ^0.24.1
  groovin_widgets: ^1.5.0+1
  animations: ^1.0.0+5
  flutter_markdown: ^0.4.0
  intl: ^0.16.1
  timeago: ^2.0.26
  wiredash: ^0.0.1+1
  syntax_highlighter: ^0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true